listener 1883
allow_anonymous false
password_file /mosquitto/config/passwd

persistence true
persistence_location /mosquitto/data/
autosave_interval 300

log_dest stdout
log_type error
log_type warning
log_type notice

max_queued_messages 10000
